# prometheus.yml
global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'nestjs-app'
    static_configs:
      - targets: ['nestjs-app:3000'] # Nome do serviço e porta INTERNA do container
    metrics_path: /metrics