name: NestJS CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x] # Matches Dockerfile node:18-alpine

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install pnpm
      run: npm install -g pnpm

    - name: Install dependencies
      run: pnpm install

    - name: Lint code
      run: pnpm run lint

    - name: Build application
      run: pnpm run build

    - name: Run unit and integration tests
      run: pnpm run test

    - name: Run E2E tests
      run: pnpm run test:e2e

